// <auto-generated />
using DuckTaleIT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DuckTaleIT.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210315162428_BasicTable")]
    partial class BasicTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DuckTaleIT.Models.MasterClass", b =>
                {
                    b.Property<int>("mClassId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive");

                    b.Property<string>("mClassCode");

                    b.Property<string>("mClassName");

                    b.HasKey("mClassId");

                    b.ToTable("MasterClass","dbo");
                });

            modelBuilder.Entity("DuckTaleIT.Models.MasterStudent", b =>
                {
                    b.Property<int>("StuId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("mClassName");

                    b.HasKey("StuId");

                    b.HasIndex("mClassName");

                    b.ToTable("MasterStudent","dbo");
                });

            modelBuilder.Entity("DuckTaleIT.Models.MasterSubject", b =>
                {
                    b.Property<int>("mSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive");

                    b.Property<string>("mSubjectCode");

                    b.Property<string>("mSubjectName");

                    b.HasKey("mSubjectId");

                    b.ToTable("MasterSubject","dbo");
                });

            modelBuilder.Entity("DuckTaleIT.Models.SubjectStudentWise", b =>
                {
                    b.Property<int>("sswId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive");

                    b.Property<int>("sswStudentId");

                    b.Property<decimal>("sswStudentMarks");

                    b.Property<int>("sswSubjectId");

                    b.HasKey("sswId");

                    b.HasIndex("sswStudentId");

                    b.HasIndex("sswSubjectId");

                    b.ToTable("SubjectStudentWise","dbo");
                });

            modelBuilder.Entity("DuckTaleIT.Models.MasterStudent", b =>
                {
                    b.HasOne("DuckTaleIT.Models.MasterClass", "masterClass")
                        .WithMany()
                        .HasForeignKey("mClassName")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DuckTaleIT.Models.SubjectStudentWise", b =>
                {
                    b.HasOne("DuckTaleIT.Models.MasterStudent", "masterStudent")
                        .WithMany()
                        .HasForeignKey("sswStudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DuckTaleIT.Models.MasterSubject", "masterSubject")
                        .WithMany()
                        .HasForeignKey("sswSubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
